# Generated by Django 5.1.2 on 2024-10-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customuser_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='initial_score',
        ),
    ]
