# Generated by Django 5.1.2 on 2024-10-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_customuser_initial_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='initial_score',
            field=models.IntegerField(default=0),
        ),
    ]
