# Generated by Django 5.1.2 on 2024-10-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_customuser_initial_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='knowledge_levels',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
