# Generated by Django 5.1.2 on 2024-10-10 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_customuser_knowledge_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_development', models.CharField(blank=True, max_length=20, null=True)),
                ('data_science', models.CharField(blank=True, max_length=20, null=True)),
                ('graphic_design', models.CharField(blank=True, max_length=20, null=True)),
                ('ai_ml', models.CharField(blank=True, max_length=20, null=True)),
                ('marketing', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
