# Generated by Django 5.1.2 on 2024-10-10 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_knowledgelevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgelevel',
            name='ai_ml',
        ),
        migrations.RemoveField(
            model_name='knowledgelevel',
            name='data_science',
        ),
        migrations.RemoveField(
            model_name='knowledgelevel',
            name='graphic_design',
        ),
        migrations.RemoveField(
            model_name='knowledgelevel',
            name='marketing',
        ),
        migrations.RemoveField(
            model_name='knowledgelevel',
            name='web_development',
        ),
        migrations.AddField(
            model_name='knowledgelevel',
            name='level',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='knowledgelevel',
            name='topic',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='knowledgelevel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
