# Generated by Django 5.1.2 on 2024-10-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_knowledgelevel_ai_ml_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='knowledge_levels',
        ),
        migrations.AlterField(
            model_name='knowledgelevel',
            name='level',
            field=models.CharField(default='Beginner', max_length=20),
        ),
    ]
